In [1]:
import pandas as pd

In [3]:
pd.DataFrame({'id':[1],'name':['a']},index=[0,1])

id name
0   1    a
1   1    a

In [5]:
pd.DataFrame([[1,'a'],[2,'b']],columns=['id','name'],index=[0,1])

id name
0   1    a
1   2    b

In [8]:
import numpy as np

In [9]:
list1=[1,2,3,4,5]

In [10]:
list1+10

TypeError: can only concatenate list (not "int") to list

In [11]:
arr1 = np.array([1,2,3,4,5])

In [12]:
arr1+10

array([11, 12, 13, 14, 15])

In [13]:
arr1/2

array([0.5, 1. , 1.5, 2. , 2.5])

In [14]:
len(arr1)

5

In [15]:
type(arr1)

numpy.ndarray

In [16]:
type(arr1[0])

numpy.int32

In [17]:
arr1.dtype

dtype('int32')

In [18]:
arr1.ndim

1

In [19]:
arr1

array([1, 2, 3, 4, 5])

In [20]:
arr1[-1]

5

In [21]:
arr1[:3]

array([1, 2, 3])

In [24]:
arr1[-1::-1]

array([5, 4, 3, 2, 1])

In [27]:
arr2=np.array([1,2,'1'])

In [28]:
arr2

array(['1', '2', '1'], dtype='<U11')

In [32]:
list(range(0,10,2))

[0, 2, 4, 6, 8]

In [33]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [36]:
arr1

array([1, 2, 3, 4, 5])

In [37]:
arr2

array(['1', '2', '1'], dtype='<U11')

In [38]:
arr1+arr2

TypeError: ufunc 'add' did not contain a loop with signature matching types dtype('<U11') dtype('<U11') dtype('<U11')

In [41]:
arr2=[5,6,7,8,9]

In [42]:
arr1+arr2

array([ 6,  8, 10, 12, 14])

In [43]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [44]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [45]:
arr_mdim = np.array([[1,2,3,4],[5,6,7,4]])

In [46]:
arr_mdim

array([[1, 2, 3, 4],
       [5, 6, 7, 4]])

In [47]:
arr_mdim.shape

(2, 4)

In [48]:
arr_mdim.ndim

2

In [50]:
arr_mdim[:,2]

array([3, 7])

In [51]:
arr_mdim[1,:]

array([5, 6, 7, 4])

In [52]:
arr_mdim[:,2]

array([3, 7])

In [53]:
arr_mdim[1,2]

7

In [54]:
arr_mdim

array([[1, 2, 3, 4],
       [5, 6, 7, 4]])

In [55]:
arr5 = np.arange(35)

In [56]:
arr5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34])

In [57]:
arr5.shape=(5,7)

In [58]:
arr5

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [59]:
arr6 = np.arange(35)

In [60]:
arr6.shape=(6,7)

ValueError: cannot reshape array of size 35 into shape (6,7)

In [63]:
arr6 = arr5.reshape(7,5)

In [62]:
arr5

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [64]:
arr5

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [65]:
arr5.shape=(1,35)

In [66]:
arr5

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34]])

In [70]:
arr10=np.array([1,2,3,4,5,6])

In [71]:
arr10.argmax()

5

In [72]:
arr10[arr10.argmax()]

6

In [73]:
arr10.max()

6

In [74]:
arr10.argmin()

0

In [75]:
arr10.argsort()

array([0, 1, 2, 3, 4, 5], dtype=int64)

In [76]:
arr10

array([1, 2, 3, 4, 5, 6])

In [78]:
arr10[arr10>3]

array([4, 5, 6])

In [80]:
arr10[3]=10

In [82]:
arr10[arr10==5]=10

In [83]:
arr10

array([ 1,  2,  3, 10, 10,  6])

In [84]:
np.where(arr10>5,50,0)

array([ 0,  0,  0, 50, 50, 50])

In [91]:
arr2 = np.arange(35)

In [92]:
arr2.shape=(7,5)

In [93]:
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [94]:
np.mean(arr2,axis=0)

array([15., 16., 17., 18., 19.])

In [95]:
np.mean(arr2,axis=1)

array([ 2.,  7., 12., 17., 22., 27., 32.])

In [96]:
np.sum(arr2,axis=0)

array([105, 112, 119, 126, 133])

In [98]:
np.median(arr2,axis=0)

array([15., 16., 17., 18., 19.])

In [99]:
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [100]:
arr2.astype('float')

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.],
       [25., 26., 27., 28., 29.],
       [30., 31., 32., 33., 34.]])

In [101]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [102]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [108]:
np.random.randint(5,size=100)

array([0, 3, 4, 2, 2, 0, 4, 4, 4, 0, 3, 1, 4, 1, 0, 4, 0, 2, 3, 2, 3, 0,
       2, 4, 1, 2, 2, 1, 2, 2, 3, 4, 0, 4, 3, 2, 1, 0, 4, 1, 2, 1, 0, 3,
       4, 0, 3, 0, 0, 1, 4, 2, 4, 4, 3, 3, 0, 0, 1, 0, 1, 0, 4, 2, 2, 4,
       1, 1, 4, 2, 1, 0, 2, 3, 4, 1, 4, 2, 4, 2, 0, 4, 2, 0, 4, 3, 2, 1,
       4, 4, 4, 1, 4, 3, 4, 3, 3, 4, 1, 0])

In [109]:
np.random.randint(5,10,size=100)

array([7, 7, 5, 7, 5, 9, 7, 7, 9, 8, 8, 5, 7, 6, 7, 5, 7, 7, 7, 5, 8, 5,
       6, 8, 9, 8, 9, 6, 7, 9, 5, 7, 6, 9, 6, 9, 9, 7, 7, 6, 6, 8, 7, 8,
       7, 8, 8, 7, 8, 5, 6, 9, 8, 6, 8, 9, 6, 8, 7, 8, 6, 7, 7, 6, 5, 5,
       8, 5, 7, 7, 9, 8, 9, 9, 6, 9, 5, 8, 8, 8, 8, 7, 6, 8, 6, 6, 7, 7,
       7, 9, 8, 5, 8, 9, 9, 6, 6, 5, 9, 9])

In [115]:
np.random.random(10)

array([0.90004262, 0.78035888, 0.28872871, 0.30776937, 0.32871385,
       0.81343621, 0.16504727, 0.67155442, 0.86611477, 0.94493918])

In [114]:
help(np.random.random)

Help on built-in function random_sample:

random_sample(...) method of mtrand.RandomState instance
    random_sample(size=None)
    
    Return random floats in the half-open interval [0.0, 1.0).
    
    Results are from the "continuous uniform" distribution over the
    stated interval.  To sample :math:`Unif[a, b), b > a` multiply
    the output of `random_sample` by `(b-a)` and add `a`::
    
      (b - a) * random_sample() + a
    
    Parameters
    ----------
    size : int or tuple of ints, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are drawn.  Default is None, in which case a
        single value is returned.
    
    Returns
    -------
    out : float or ndarray of floats
        Array of random floats of shape `size` (unless ``size=None``, in which
        case a single float is returned).
    
    Examples
    --------
    >>> np.random.random_sample()
    0.47108547995356098
    >>> type(np.random.random_

In [116]:
np.random.rand(10)

array([0.27628719, 0.92463737, 0.65283891, 0.90325643, 0.03610573,
       0.31121687, 0.17067469, 0.16512381, 0.18071852, 0.59534292])

In [117]:
help(np.random.rand)

Help on built-in function rand:

rand(...) method of mtrand.RandomState instance
    rand(d0, d1, ..., dn)
    
    Random values in a given shape.
    
    Create an array of the given shape and populate it with
    random samples from a uniform distribution
    over ``[0, 1)``.
    
    Parameters
    ----------
    d0, d1, ..., dn : int, optional
        The dimensions of the returned array, should all be positive.
        If no argument is given a single Python float is returned.
    
    Returns
    -------
    out : ndarray, shape ``(d0, d1, ..., dn)``
        Random values.
    
    See Also
    --------
    random
    
    Notes
    -----
    This is a convenience function. If you want an interface that
    takes a shape-tuple as the first argument, refer to
    np.random.random_sample .
    
    Examples
    --------
    >>> np.random.rand(3,2)
    array([[ 0.14022471,  0.96360618],  #random
           [ 0.37601032,  0.25528411],  #random
           [ 0.49313049,  0.94909878]]

In [118]:
bike_sharing = pd.read_csv("C:/Users/Santosh/Desktop/files/bike_sharing_python.csv")

In [119]:
bike_sharing.head()

datetime  season  holiday  workingday  weather   temp   atemp  \
0  1/20/2011 0:00     1.0      0.0         1.0      1.0  10.66  11.365   
1  1/20/2011 1:00     1.0      0.0         1.0      1.0  10.66  13.635   
2  1/20/2011 2:00     1.0      0.0         1.0      1.0  10.66  13.635   
3  1/20/2011 3:00     1.0      0.0         1.0      1.0  10.66  12.880   
4  1/20/2011 4:00     1.0      0.0         1.0      1.0  10.66  12.880   

   humidity  windspeed  
0      56.0    26.0027  
1      56.0     0.0000  
2      56.0     0.0000  
3      56.0    11.0014  
4      56.0    11.0014

In [120]:
plt.hist(bike_sharing['temp'])

NameError: name 'plt' is not defined