## NUMPY

Benefit for using Numpy 
1. Less Coding
2. Faster
3. Uses less memory as compared to Python List

In [3]:
import numpy as np

In [6]:
np

<module 'numpy' from 'C:\\Users\\tarun.dabhi\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>

In [15]:
arr = np.array([1,2,3,4,5])

In [16]:
arr

array([1, 2, 3, 4, 5])

In [17]:
arr + 10 # To add 10 in all the elements

array([11, 12, 13, 14, 15])

In [18]:
arr / 2 # To divide all the numbers from 2

array([0.5, 1. , 1.5, 2. , 2.5])

In [19]:
len(arr) # Length of an Array

5

In [20]:
type(arr)

numpy.ndarray

In [21]:
type(arr[0])

numpy.int32

In [22]:
arr.dtype

dtype('int32')

In [23]:
arr.ndim # This will give you the dimension of the array, this example is 1-D 

1

In [24]:
arr[-1] # Slicing, This will give last element

5

In [25]:
arr[::-1] # Reversse an array

array([5, 4, 3, 2, 1])

In [26]:
arr[-1::-1] # Another way to reversse an array

array([5, 4, 3, 2, 1])

In [30]:
list(range(0,10)) # This creates a list from 0 to 9

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [31]:
list(range(0,10,2)) # This creates a list from 0 to 9 with step size 2

[0, 2, 4, 6, 8]

In [32]:
np.arange(10) # Numpy way to create an Array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
np.arange(0, 10) # Another Numpy way to create an Array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
np.arange(0, 10, 2) # Another Numpy way to create an Array

array([0, 2, 4, 6, 8])

In [35]:
arr

array([1, 2, 3, 4, 5])

In [41]:
arr2 = [6,7,8,9,10]

In [42]:
arr + arr2 # This adds the elements based on the index

array([ 7,  9, 11, 13, 15])

In [43]:
np.linspace(0,10,5) # This will retuen 5 elements betweeen 0 and 10 with equal difference

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [44]:
np.linspace(0,10,20) # This will retuen 20 elements betweeen 0 and 10 with equal difference

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [50]:
arr_2dim = np.array([[1,2,3,4],[5,6,7,8]]) # This will create 2-D array

In [51]:
arr_2dim

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [52]:
arr_2dim.shape

(2, 4)

In [53]:
arr_2dim[1,:] # This will return first row all coulmn (: means all the values)

array([5, 6, 7, 8])

In [54]:
arr_2dim[1,2] # This will return value of second row and third coulmn

7

In [57]:
arr5 = np.arange(35) # This is 1-D array

In [61]:
arr5

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [62]:
arr5.shape=(5, 7) # This will convert this array into 2-D array with 5 rows and 7 columns

In [64]:
arr5 # This has been changed to 2-D array

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [65]:
arr5.shape=(6,7) # This will not work as the values are less in the array

ValueError: cannot reshape array of size 35 into shape (6,7)

In [67]:
arr5.reshape(7,5) # This is changing the shape of the array but not storing  in arr5, while shape does

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [68]:
arr5.shape=(1,35) # You can use shape for reshaping the array

In [69]:
arr5

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34]])

In [70]:
arr6 = np.array([1,2,3,4,5,6])

In [71]:
arr6

array([1, 2, 3, 4, 5, 6])

In [73]:
arr6.argmax() # This will give us the index of max value, max value is 6 and index is 5

5

In [76]:
arr6[arr6.argmax()] # Getting the max value from index

6

In [77]:
arr6.max() # This will directly give the max value, no need of getting index

6

In [78]:
arr6.argmin() # This will give us the index of min value, max value is 1 and index is 0

0

In [79]:
arr6[arr6.argmin()] # Getting the min value from index

1

In [80]:
arr6.min() # This will directly give the min value, no need of getting index

1

In [81]:
arr7 = np.array([5,6,2,9,10])

In [82]:
arr7

array([ 5,  6,  2,  9, 10])

In [84]:
arr7.argsort() # This will give the index of the sorted array

array([2, 0, 1, 3, 4], dtype=int64)

In [85]:
arr7[arr7>5]

array([ 6,  9, 10])

In [86]:
arr7[arr7>5]=50 # Replace all the value which is greater then 5 with 50

In [87]:
arr7

array([ 5, 50,  2, 50, 50])

In [95]:
arr8 = np.array([1,2,10,3,2,7,9])

In [96]:
arr8

array([ 1,  2, 10,  3,  2,  7,  9])

In [99]:
np.where(arr8>5,50,0) #This will replace value with 50 which are greater then 5 and with 0 which are less then 5

array([ 0,  0, 50,  0,  0, 50, 50])

In [100]:
arr9 = np.arange(35)

In [101]:
arr9.shape=(7,5)

In [102]:
arr9

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [103]:
np.mean(arr9,axis=0) # mean by column, axis = 0 is column in numpy

array([15., 16., 17., 18., 19.])

In [105]:
np.mean(arr9,axis=1) # mean by row

array([ 2.,  7., 12., 17., 22., 27., 32.])

In [107]:
np.sum(arr9,axis=0) # sum by column

array([105, 112, 119, 126, 133])

In [109]:
np.median(arr9,axis=0) # midian value by column

array([15., 16., 17., 18., 19.])

In [113]:
numpy_col = 0 # Create variable to avoid confusion

In [114]:
np.sum(arr9,axis=numpy_col) # sum by column

array([105, 112, 119, 126, 133])

In [115]:
arr9

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [117]:
arr9.astype("float") # changing the datatype to float

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.],
       [25., 26., 27., 28., 29.],
       [30., 31., 32., 33., 34.]])

In [119]:
np.ones(5) # This will create a array with the length 5 with all the values as 1

array([1., 1., 1., 1., 1.])

In [121]:
np.zeros(5) # This will create a array with the length 5 with all the values as 0

array([0., 0., 0., 0., 0.])

In [123]:
np.random.randint(5,10,size=20) # This will give 20 random numbers between 5 and 10

array([7, 7, 6, 9, 7, 8, 9, 9, 5, 7, 6, 5, 8, 8, 6, 9, 9, 8, 7, 7])

In [163]:
np.random.random(5) 

array([0.47736646, 0.4694381 , 0.13994422, 0.55845686, 0.17371868])

In [165]:
np.random.rand(5)

array([0.24667649, 0.11820968, 0.83647762, 0.69450015, 0.90976604])